import Head from 'next/head';

const Home = () => (
  <>
    <Head>
      <title>Project Starter</title>
      <meta content="Generated by create next app" name="description" />
      <link href="/favicon.ico" rel="icon" />
    </Head>

    <main className="text-3xl font-bold underline bg-red-300">
      <div>
        Hello Tailwind!
      </div>
    </main>
  </>
);
export default Home;
